name: xmonad-atif
version: 0.16
synopsis: My xmonad configuration.
license: MIT
author: Atif
maintainer: iftakhar.awal@yahoo.com
homepage: https://github.com/AtifChy/dotfiles

ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints -O2 -j -dynamic

dependencies:
  - base
  - xmonad-contrib >= 0.16

source-dirs: src

executables:
  xmonad:
    main: xmonad.hs
    dependencies:
      - xmonad
      - containers
      - X11 >= 1.10
  xmobar:
    main: xmobar.hs
    dependencies:
      - xmobar
    ghc-options: -rtsopts -threaded -with-rtsopts=-N
