#!/usr/bin/env sh

SPEAKER=1
MICROPHONE=0

case $1 in
        -i)
                DATA=$(pamixer --get-volume)
                [ "$DATA" -lt '200' ] && pamixer --allow-boost -u -i 5
                ;;
        -d)
                pamixer --allow-boost -u -d 5
                ;;
        -t)
                pamixer -t
                ;;
        -mi)
                pamixer --default-source -u -i 5
                ;;
        -md)
                pamixer --default-source -u -d 5
                ;;
        -mt)
                pamixer --default-source -t
                ;;
esac

if [ "$SPEAKER" = '1' ]; then
        STATUSPIPE="/tmp/xmobar_volume"
        [ -e "$STATUSPIPE" ] || mkfifo "$STATUSPIPE"

        DATA=$(pamixer --get-volume-human)

        if [ "$DATA" = 'muted' ]; then
                printf "<fc=#ff6c6b><fn=1></fn></fc> %s\n" "$DATA" >$STATUSPIPE
                exit
        else
                DATA=$(pamixer --get-volume)
        fi

        if [ "$DATA" -ge '60' ]; then
                printf "<fc=#98be65><fn=1></fn></fc> %s%%\n" "$DATA" >$STATUSPIPE
                exit
        fi

        if [ "$DATA" -ge '20' ]; then
                printf "<fc=#ecbe8b><fn=1></fn></fc> %s%%\n" "$DATA" >$STATUSPIPE
                exit
        fi

        if [ "$DATA" -ge '0' ]; then
                printf "<fc=#ff6c6b><fn=1></fn></fc> %s%%\n" "$DATA" >$STATUSPIPE
                exit
        fi
fi

if [ "$MICROPHONE" = '1' ]; then
        STATUSPIPE2="/tmp/xmobar_mic"
        [ -e "$STATUSPIPE2" ] || mkfifo "$STATUSPIPE2"

        DATA2=$(pamixer --default-source --get-volume-human)

        if [ "$DATA" = 'muted' ]; then
                printf "<fc=#ff6c6b><fn=1></fn></fc> %s\n" "$DATA2" >$STATUSPIPE2
                exit
        else
                DATA=$(pamixer --default-source --get-volume)
        fi

        if [ "$DATA" -ge '60' ]; then
                printf "<fc=#98be65><fn=1></fn></fc> %s%%\n" "$DATA2" >$STATUSPIPE2
                exit
        fi

        if [ "$DATA" -ge '20' ]; then
                printf "<fc=#ecbe8b><fn=1></fn></fc> %s%%\n" "$DATA2" >$STATUSPIPE2
                exit
        fi

        if [ "$DATA" -ge '0' ]; then
                printf "<fc=#ff6c6b><fn=1></fn></fc> %s%%\n" "$DATA2" >$STATUSPIPE2
                exit
        fi
fi
