#!/bin/sh

sel() {
	scrot -a $(slop -f '%x,%y,%w,%h') '%d-%m-%Y_%H-%M-%S.png' -e 'xclip -selection clipboard -target image/png -i $f ; mv $f ~/Pictures';
	notify-send --icon=gnome-screenshot 'Scrot' 'Screenshot of selected screen saved'
}

win() {
	scrot -u '%d-%m-%Y_%H-%M-%S.png' -e 'xclip -selection clipboard -target image/png -i $f ; mv $f ~/Pictures';
	notify-send --icon=gnome-screenshot 'Scrot' 'Screenshot of focused window saved'
}

ful() {
	scrot '%d-%m-%Y_%H-%M-%S.png' -e 'xclip -selection clipboard -target image/png -i $f ; mv $f ~/Pictures';
	notify-send --icon=gnome-screenshot 'Scrot' 'Fullscreen screenshot saved'
}

case $1 in
	sel|win|ful) "$1" ;;
esac
