#!/bin/sh

wall_dir=$HOME/Pictures/Wallpapers
cached_wall=${XDG_CACHE_DIR:-$HOME/.cache}/wallpaper.sh

wallpaper() {
        hsetroot -cover "$1"
        cat <<EOF >"$cached_wall"
#!/bin/sh
hsetroot -cover $1
EOF
        [ -x "$cached_wall" ] || chmod +x "$cached_wall"
}

random() {
        img=$(find "$wall_dir" -type f | grep -v -E 'git|README.md' | shuf -n1)
        hsetroot -cover "$img"
}

daemon() {
        while :; do
                random
                sleep 10m
        done
}

case $1 in
        *.png | *.jpg) wallpaper "$1" ;;
        random) random ;;
        daemon) daemon ;;
        *) $cached_wall || random ;;
esac
